on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: FTP Deploy to WP Engine (Staging)
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: sftp://velius.zapto.org:22/public/
        ftp-username: vDocs
        ftp-password: ${{ secrets.SSH_PRIVATE_KEY }}
        local-dir: ./docs/.vuepress/dist
